import puppeteer from 'puppeteer-core'
const out = process.argv[2]
const W = Number(process.argv[3] ?? 1440), H = Number(process.argv[4] ?? 900)
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: 'new', args: ['--hide-scrollbars', '--use-gl=angle', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage()
await page.setViewport({ width: W, height: H })
page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
page.on('console', (m) => (m.type() === 'error') && console.log('CONSOLE', m.text().slice(0, 300)))
await page.evaluateOnNewDocument(() => { try { sessionStorage.setItem('intro-seen', '1') } catch {} })
await page.goto('http://localhost:4173/Your-Life-In-Receipts/', { waitUntil: 'networkidle0' })
const wait = (ms) => new Promise((r) => setTimeout(r, ms))
await wait(2500)
await page.screenshot({ path: `${out}/w1-hook-printing.png` })
await wait(9000)
await page.screenshot({ path: `${out}/w1-hook.png` })
const go = async (id, name, frac = 0) => {
  await page.evaluate((id, frac) => { const el = document.getElementById(`act-${id}`); const top = el.getBoundingClientRect().top + window.scrollY; window.scrollTo(0, top + (el.offsetHeight - innerHeight) * frac) }, id, frac)
  await wait(3500)
  await page.screenshot({ path: `${out}/${name}.png` })
}
await go('river', 'w2-river-a', 0.05)
await go('river', 'w2-river-b', 0.5)
await go('threads', 'w3-threads', 0.1)
await page.evaluate(() => document.getElementById('act-roll').scrollIntoView()); await wait(1500)
await go('roll', 'w4-roll', 0.45)
await go('end', 'w5-end', 0.3)
await browser.close()
console.log('ok')
